addons:
  code_climate:
    repo_token:
      secure: 'i146lmmBHbhAAoThe1C1L6bEvVpWBlB5IyBG+Uvlcgtb1GJGrm3LN4BQPyHYKAxCPSAz14viKFJC7xZ+TfFxHP0vkjV2+NjJtU3fcW220IFRV0Xx3hgDVi1e3yvXFrhJPxX6I3D9UNgONqgxMDAcGwJmzJt7EPuR3Vlolu7STPuDN89ybzJHRJgp4Ai6b+skdETzD3ZJusTsAHyGhSAYLqNGyMtJs69Vogjdudt1qA8wwgchXqWCYycRhZGj9cztadYvsYfA49YASCHASu3OhRIWd7LGLCFy9tj/wGngGkQThaOUVbKodBMAhYIW+uAQP5Jlat1VYgtHmSJzdWaGbVEpv9uMS3wcNI3n4uV3sS9NyJazgjPQN5VnCPOKJsval1Fp0QV/RbWV+fMxxsnXfUWUjCUklqqpbUDXnboqY2Y2RDzfSvM4b3tUxj3AHvj9nNuy7QA12clJg9QE5Q23cqOHsDkbRnhPT99pc6JxX3vgyAOzjz6L5Hy3xQSc+RtQ6Q5tfZ9owbfDSpsWVBR+b49HPQHJIoZN4bAuhm3TAucM0mf9Zeaa8vgmcSXm6Hwhv+RN2S6DrVwrw9vFL8JAgRuaa0SMrKywgQeGfC+dXrK3vHMr72nAKbEf9beAZgRfoR0OqJ49xPAxCm666TeD6ssolcKUGpqacNZ7dS0mHVw='
after_success:
  - bundle exec codeclimate-test-reporter
before_install:
  - gem update bundler rake
branches:
  only:
    - master
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.3'
  - '2.4.0'
  - '2.4.1'
  - ruby-head
script:
  - bundle exec rspec
  - bundle exec rubocop
